#!/usr/bin/env bash

code --install-extension vscodevim.vim
code --install-extension ms-vscode.go
code --install-extension dracula-theme.theme-dracula
code --install-extension jakebecker.elixir-ls
code --install-extension PeterJausovec.vscode-docker
code --install-extension editorconfig.editorconfig
code --install-extension iampeterbanjo.elixirlinter
code --install-extension eamodio.gitlens
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mohsen1.react-javascript-to-typescript-transform-vscode
code --install-extension wholroyd.jinja
code --install-extension silvenon.mdx
code --install-extension ms-vscode.node-debug2
code --install-extension foxundermoon.shell-format
code --install-extension mauve.terraform
code --install-extension mjmcloug.vscode-elixir
code --install-extension sammkj.vscode-elixir-formatter
code --install-extension redhat.vscode-yaml
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension shan.code-settings-sync
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension redhat.vscode-yaml
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension davidanson.vscode-markdownlint
code --install-extension esbenp.prettier-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension dbaeumer.vscode-eslint
